from exceptions.exception_base import ExceptionBase


class CantBeUndone(ExceptionBase):
    pass
