from exceptions.exception_base import ExceptionBase


class RuntimeError(ExceptionBase):
    pass
